-- Seed data for exercises

insert into public.exercises (title, duration_minutes, intensity, equipment, instructions, tips, category, movement_tags, body_region_tags, context_tags, location_tags, contraindication_tags, requires_floor, standing_only, no_sweat, variation_key)
values
  (
    'Desk-Side Stretching Sequence',
    5,
    'low',
    array['None / Bodyweight Only'],
    array['Stand behind your chair', 'Reach arms overhead for 30 seconds', 'Side bends - 10 each side', 'Gentle torso twists', 'Neck rolls - 5 each direction'],
    'Perfect for between meetings. No changing required.',
    'Mobility',
    array['spinal_mobility', 'shoulder_mobility'],
    array['neck_upper_back', 'shoulders'],
    array['office_friendly', 'low_sweat', 'camera_safe'],
    array['Workplace', 'Home Office'],
    array[]::text[],
    false,
    true,
    true,
    'desk-mobility'
  ),
  (
    'Standing Leg Activators',
    7,
    'low',
    array['Chair'],
    array['Use chair for balance if needed', 'Calf raises - 15 reps', 'Single leg balance - 30 sec each', 'Gentle leg swings - 10 each direction', 'Standing glute squeezes - 20 reps'],
    'Great for improving circulation during long work sessions.',
    'Activation',
    array['balance', 'gait_or_march'],
    array['hips_glutes', 'ankles_calves'],
    array['office_friendly', 'low_sweat'],
    array['Workplace', 'Home Office', 'Living Room'],
    array['Ankle Issues'],
    false,
    true,
    true,
    'standing-lower-activation'
  ),
  (
    'Wall-Assisted Upper Body',
    8,
    'medium',
    array['Wall Space'],
    array['Wall push-ups - 12 reps', 'Wall angels - 15 reps', 'Wall slides - 10 reps', 'Shoulder blade squeezes against wall', 'Chest stretch using doorframe'],
    'Builds upper body strength without equipment.',
    'Strength',
    array['upper_push', 'shoulder_mobility'],
    array['shoulders', 'thoracic_spine'],
    array['home_friendly', 'small_space'],
    array['Home Office', 'Living Room', 'Bedroom'],
    array['Shoulder Injury', 'Wrist Problems'],
    false,
    true,
    false,
    'wall-upper-strength'
  ),
  (
    'Meeting Break Posture Reset',
    3,
    'low',
    array['None / Bodyweight Only'],
    array['Stand tall with feet under hips', 'Roll shoulders back for 30 seconds', 'Open arms into a wide chest stretch', 'Reach long through the crown of the head'],
    'Ideal before turning your camera back on.',
    'Mobility',
    array['spinal_mobility', 'shoulder_mobility'],
    array['neck_upper_back', 'thoracic_spine'],
    array['office_friendly', 'camera_safe', 'low_sweat'],
    array['Workplace', 'Home Office'],
    array[]::text[],
    false,
    true,
    true,
    'posture-reset'
  ),
  (
    'Chair Hip Wake-Up',
    5,
    'low',
    array['Chair'],
    array['Sit tall near the front of the chair', 'March slowly for 45 seconds', 'Extend one leg at a time', 'Stand and perform 10 gentle hip hinges'],
    'A smooth transition from sitting to moving.',
    'Activation',
    array['gait_or_march', 'hip_hinge'],
    array['hips_glutes', 'core'],
    array['office_friendly', 'low_sweat'],
    array['Workplace', 'Home Office', 'Living Room'],
    array['Hip Pain'],
    false,
    false,
    true,
    'chair-hip-activation'
  ),
  (
    'Countertop Calf and Core Flow',
    5,
    'low',
    array['Countertop'],
    array['Place hands on countertop', 'Perform 15 calf raises', 'Step back into an incline plank hold for 20 seconds', 'Alternate knee drives for 20 seconds'],
    'Turns a kitchen counter into a quick stability station.',
    'Activation',
    array['core', 'gait_or_march'],
    array['ankles_calves', 'core'],
    array['home_friendly', 'low_sweat'],
    array['Living Room', 'Home Office'],
    array['Wrist Problems'],
    false,
    true,
    true,
    'countertop-core'
  ),
  (
    'Wall Sit Focus Builder',
    3,
    'medium',
    array['Wall Space'],
    array['Lean against a wall and slide into a shallow sit', 'Hold for 20 seconds', 'Stand and shake out the legs', 'Repeat 3 rounds'],
    'A short burst when you want to feel more switched on.',
    'Strength',
    array['squat_pattern'],
    array['knees', 'hips_glutes'],
    array['small_space', 'home_friendly'],
    array['Home Office', 'Living Room', 'Bedroom'],
    array['Knee Issues'],
    false,
    true,
    false,
    'wall-leg-strength'
  ),
  (
    'Breathing Reset for Busy Days',
    3,
    'low',
    array['None / Bodyweight Only'],
    array['Sit or stand tall', 'Inhale through the nose for 4 counts', 'Exhale slowly for 6 counts', 'Repeat for 6 rounds'],
    'A recovery snack for when stress feels louder than your body.',
    'Recovery',
    array['core'],
    array['core', 'low_back'],
    array['office_friendly', 'camera_safe', 'low_sweat'],
    array['Workplace', 'Home Office', 'Bedroom'],
    array[]::text[],
    false,
    false,
    true,
    'breathing-reset'
  ),
  (
    'Doorway Shoulder Decompression',
    5,
    'low',
    array['Doorway Pull-up Bar'],
    array['Stand beneath the bar with feet grounded', 'Hold a light supported dead hang if comfortable', 'Release and perform shoulder circles', 'Finish with a chest-opening doorway stretch'],
    'Use support from the floor the entire time if full hanging is not comfortable.',
    'Mobility',
    array['upper_pull', 'shoulder_mobility'],
    array['shoulders', 'thoracic_spine'],
    array['home_friendly', 'small_space'],
    array['Bedroom', 'Living Room', 'Home Office'],
    array['Shoulder Injury', 'Wrist Problems'],
    false,
    true,
    true,
    'doorway-decompression'
  ),
  (
    'Living Room Core Brace Circuit',
    7,
    'medium',
    array['Yoga Mat'],
    array['Lie on your back with knees bent', 'Perform 8 dead bugs per side', 'Hold a glute bridge for 30 seconds', 'Finish with 20 seconds of tabletop breathing'],
    'A compact core circuit with no complicated setup.',
    'Strength',
    array['core'],
    array['core', 'hips_glutes'],
    array['home_friendly'],
    array['Living Room', 'Bedroom'],
    array['Back Pain', 'Hip Pain'],
    true,
    false,
    false,
    'mat-core-strength'
  ),
  (
    'Standing Spine Unwind',
    5,
    'low',
    array['None / Bodyweight Only'],
    array['Stand tall and soften your knees', 'Roll down halfway with control', 'Return to standing', 'Add 10 gentle torso rotations'],
    'A reliable reset after too much sitting.',
    'Recovery',
    array['spinal_mobility', 'rotation'],
    array['low_back', 'thoracic_spine'],
    array['office_friendly', 'low_sweat'],
    array['Workplace', 'Home Office', 'Living Room'],
    array['Back Pain'],
    false,
    true,
    true,
    'spine-unwind'
  ),
  (
    'Band Pull-Apart Primer',
    5,
    'low',
    array['Resistance Bands'],
    array['Stand tall and hold the band at chest height', 'Perform 12 pull-aparts', 'Raise the band overhead for 8 controlled reps', 'Repeat 2 rounds'],
    'Excellent before a workout or after a long block at your desk.',
    'Activation',
    array['upper_pull', 'shoulder_mobility'],
    array['shoulders', 'thoracic_spine'],
    array['home_friendly', 'low_sweat'],
    array['Home Office', 'Living Room', 'Gym'],
    array['Shoulder Injury'],
    false,
    true,
    true,
    'band-upper-activation'
  ),
  (
    'Dumbbell Suitcase March',
    7,
    'medium',
    array['Dumbbells'],
    array['Hold one dumbbell by your side', 'March in place for 30 seconds', 'Switch hands and repeat', 'Complete 4 rounds'],
    'Challenges core control without needing much space.',
    'Strength',
    array['core', 'gait_or_march'],
    array['core', 'hips_glutes'],
    array['home_friendly', 'small_space'],
    array['Living Room', 'Gym', 'Home Office'],
    array['Back Pain', 'Shoulder Injury'],
    false,
    true,
    false,
    'dumbbell-march'
  ),
  (
    'Floor-Based Hip Release',
    10,
    'low',
    array['Floor Space', 'Yoga Mat'],
    array['Sit on the floor with one leg bent', 'Perform gentle hip switches', 'Hold a figure-four stretch for 30 seconds each side', 'Finish with a seated forward fold'],
    'A slower snack for when your hips feel locked up.',
    'Recovery',
    array['hip_mobility'],
    array['hips_glutes', 'low_back'],
    array['home_friendly'],
    array['Living Room', 'Bedroom'],
    array['Hip Pain', 'Knee Issues'],
    true,
    false,
    true,
    'floor-hip-release'
  ),
  (
    'Workday March and Reach',
    3,
    'low',
    array['None / Bodyweight Only'],
    array['March in place for 45 seconds', 'Reach both arms overhead for 20 seconds', 'Return to marching', 'Finish with ankle circles'],
    'A fast way to feel more awake without breaking a sweat.',
    'Activation',
    array['gait_or_march', 'shoulder_mobility'],
    array['ankles_calves', 'shoulders'],
    array['office_friendly', 'camera_safe', 'low_sweat'],
    array['Workplace', 'Home Office'],
    array['Ankle Issues'],
    false,
    true,
    true,
    'workday-march'
  ),
  (
    'Chair-Supported Split Stance Hold',
    5,
    'medium',
    array['Chair'],
    array['Stand beside a chair for support', 'Step one foot back into a split stance', 'Lower slightly and hold for 20 seconds', 'Switch sides and repeat 3 rounds'],
    'Good for leg strength without needing much room.',
    'Strength',
    array['squat_pattern', 'balance'],
    array['hips_glutes', 'knees'],
    array['home_friendly', 'small_space'],
    array['Home Office', 'Living Room'],
    array['Knee Issues', 'Hip Pain'],
    false,
    true,
    false,
    'chair-leg-strength'
  ),
  (
    'Wrist-Friendly Forearm Wake-Up',
    3,
    'low',
    array['None / Bodyweight Only'],
    array['Extend arms forward', 'Open and close the hands for 20 reps', 'Perform gentle wrist circles', 'Finish with forearm stretches'],
    'A useful desk-side reset before typing again.',
    'Mobility',
    array['shoulder_mobility'],
    array['wrists_forearms', 'shoulders'],
    array['office_friendly', 'camera_safe', 'low_sweat'],
    array['Workplace', 'Home Office'],
    array[]::text[],
    false,
    true,
    true,
    'forearm-reset'
  ),
  (
    'Gentle Backline Lengthener',
    7,
    'low',
    array['Chair'],
    array['Place hands on the chair back', 'Step back and lengthen your spine', 'Bend and straighten the knees gently', 'Finish with a supported hamstring stretch'],
    'Lets you unwind the back of the body without getting on the floor.',
    'Mobility',
    array['hip_hinge', 'spinal_mobility'],
    array['low_back', 'hips_glutes'],
    array['office_friendly', 'low_sweat'],
    array['Home Office', 'Workplace', 'Living Room'],
    array['Back Pain'],
    false,
    true,
    true,
    'backline-mobility'
  ),
  (
    'Band Lateral Step Series',
    7,
    'medium',
    array['Resistance Bands'],
    array['Place the band above your knees', 'Take 8 lateral steps each direction', 'Perform 10 mini squats', 'Repeat 3 rounds'],
    'A compact lower-body snack with a little more challenge.',
    'Strength',
    array['lateral_shift', 'squat_pattern'],
    array['hips_glutes', 'knees'],
    array['home_friendly'],
    array['Living Room', 'Gym'],
    array['Knee Issues', 'Hip Pain'],
    false,
    true,
    false,
    'band-lateral-strength'
  ),
  (
    'Morning Bedroom Mobility Flow',
    10,
    'low',
    array['Yoga Mat'],
    array['Start in a tall kneeling position', 'Reach one arm overhead and side bend', 'Move into a supported half-kneeling hip stretch', 'Finish with slow cat-cow breathing'],
    'Designed to gently start the day instead of shocking your system.',
    'Mobility',
    array['hip_mobility', 'spinal_mobility'],
    array['hips_glutes', 'thoracic_spine'],
    array['home_friendly'],
    array['Bedroom', 'Living Room'],
    array['Knee Issues'],
    true,
    false,
    true,
    'morning-mobility'
  ),
  (
    'Outdoor Walk Prep Sequence',
    5,
    'low',
    array['None / Bodyweight Only'],
    array['Stand tall and march for 30 seconds', 'Perform ankle rolls', 'Do 10 standing knee lifts', 'Finish with arm swings'],
    'A clean transition into a walk outside.',
    'Activation',
    array['gait_or_march', 'balance'],
    array['ankles_calves', 'hips_glutes'],
    array['outdoor_friendly', 'low_sweat'],
    array['Outdoor Space', 'Living Room'],
    array['Ankle Issues'],
    false,
    true,
    true,
    'walk-prep'
  ),
  (
    'Doorframe Chest Opener',
    3,
    'low',
    array['Wall Space'],
    array['Place one forearm on a doorway', 'Step gently through the doorway', 'Hold for 20 seconds', 'Switch sides and repeat'],
    'A tiny posture reset after hunching over a laptop.',
    'Recovery',
    array['shoulder_mobility'],
    array['shoulders', 'thoracic_spine'],
    array['office_friendly', 'low_sweat', 'camera_safe'],
    array['Workplace', 'Home Office', 'Bedroom'],
    array['Shoulder Injury'],
    false,
    true,
    true,
    'doorframe-chest-open'
  ),
  (
    'Chair Core Compression Reset',
    5,
    'low',
    array['Chair'],
    array['Sit tall near the edge of the chair', 'Lift one knee and brace the core', 'Alternate for 20 reps total', 'Add 10 seated torso reaches'],
    'A discreet core snack you can do without leaving your seat.',
    'Activation',
    array['core'],
    array['core', 'hips_glutes'],
    array['office_friendly', 'camera_safe', 'low_sweat'],
    array['Workplace', 'Home Office'],
    array['Hip Pain'],
    false,
    false,
    true,
    'chair-core-activation'
  ),
  (
    'Wall Balance Builder',
    5,
    'low',
    array['Wall Space'],
    array['Stand next to the wall', 'Lift one knee and balance for 20 seconds', 'Tap the wall lightly as needed', 'Switch sides and repeat 3 rounds'],
    'Useful when you want control and stability more than intensity.',
    'Activation',
    array['balance'],
    array['ankles_calves', 'hips_glutes'],
    array['office_friendly', 'low_sweat', 'small_space'],
    array['Home Office', 'Workplace', 'Living Room'],
    array['Ankle Issues'],
    false,
    true,
    true,
    'wall-balance'
  ),
  (
    'Dumbbell Hinge Micro-Set',
    10,
    'medium',
    array['Dumbbells'],
    array['Hold a pair of dumbbells by your sides', 'Perform 10 controlled hinges', 'Rest for 20 seconds', 'Repeat 3 rounds'],
    'Short, simple strength work for the back side of the body.',
    'Strength',
    array['hip_hinge'],
    array['hips_glutes', 'low_back'],
    array['home_friendly'],
    array['Living Room', 'Gym'],
    array['Back Pain', 'Hip Pain'],
    false,
    true,
    false,
    'dumbbell-hinge'
  ),
  (
    'Mat Glute Bridge Ladder',
    10,
    'medium',
    array['Yoga Mat', 'Floor Space'],
    array['Lie on your back with knees bent', 'Perform 10 glute bridges', 'Hold the top position for 20 seconds', 'Repeat 3 rounds'],
    'A dependable lower-body snack that does not require a full workout.',
    'Strength',
    array['hip_hinge', 'core'],
    array['hips_glutes', 'core'],
    array['home_friendly'],
    array['Living Room', 'Bedroom'],
    array['Back Pain', 'Hip Pain'],
    true,
    false,
    false,
    'glute-bridge'
  ),
  (
    'Seated Neck and Shoulder Melt',
    5,
    'low',
    array['Chair'],
    array['Sit tall with feet planted', 'Drop one ear toward one shoulder', 'Hold for 20 seconds', 'Repeat on the other side and finish with shoulder rolls'],
    'A great reset at the end of a screen-heavy block.',
    'Recovery',
    array['shoulder_mobility'],
    array['neck_upper_back', 'shoulders'],
    array['office_friendly', 'camera_safe', 'low_sweat'],
    array['Workplace', 'Home Office', 'Bedroom'],
    array[]::text[],
    false,
    false,
    true,
    'seated-neck-recovery'
  ),
  (
    'Standing Hip Airplane Prep',
    7,
    'medium',
    array['Wall Space'],
    array['Stand beside a wall for support', 'Lift one foot behind you slightly', 'Hinge forward and rotate the hips open', 'Switch sides and repeat'],
    'Excellent for balance and glute control when you want a bit more challenge.',
    'Activation',
    array['balance', 'hip_hinge'],
    array['hips_glutes', 'core'],
    array['home_friendly', 'small_space'],
    array['Living Room', 'Home Office'],
    array['Ankle Issues', 'Hip Pain'],
    false,
    true,
    false,
    'hip-airplane-prep'
  ),
  (
    'Home Office Push-Up Progression',
    7,
    'medium',
    array['Countertop'],
    array['Place hands on the countertop', 'Perform 8 incline push-ups', 'Rest for 20 seconds', 'Repeat 3 rounds'],
    'A practical upper-body strength option when floor push-ups are not realistic.',
    'Strength',
    array['upper_push'],
    array['shoulders', 'core'],
    array['home_friendly', 'small_space'],
    array['Home Office', 'Living Room'],
    array['Shoulder Injury', 'Wrist Problems'],
    false,
    true,
    false,
    'incline-push-up'
  ),
  (
    'Low-Back Offload Sequence',
    12,
    'low',
    array['Yoga Mat'],
    array['Lie on your back with feet on the floor', 'Pull one knee in gently', 'Switch sides', 'Finish with long exhalations and pelvic tilts'],
    'A quieter snack for evenings when your back feels cranky.',
    'Recovery',
    array['spinal_mobility'],
    array['low_back', 'hips_glutes'],
    array['home_friendly'],
    array['Bedroom', 'Living Room'],
    array['Hip Pain'],
    true,
    false,
    true,
    'low-back-recovery'
  ),
  (
    'Conference Call Circulation Boost',
    5,
    'low',
    array['None / Bodyweight Only'],
    array['Stand and perform heel-to-toe rocks', 'March in place quietly', 'Add 10 arm circles forward and backward', 'Finish with deep breaths'],
    'Designed to keep you moving while you are still listening.',
    'Activation',
    array['gait_or_march'],
    array['ankles_calves', 'shoulders'],
    array['office_friendly', 'camera_safe', 'low_sweat'],
    array['Workplace', 'Home Office'],
    array['Ankle Issues'],
    false,
    true,
    true,
    'call-circulation'
  ),
  (
    'Band Row Posture Builder',
    10,
    'medium',
    array['Resistance Bands'],
    array['Anchor the band safely at chest height', 'Perform 12 rows', 'Hold the squeeze for 2 seconds each rep', 'Repeat 3 rounds'],
    'Adds a true pulling pattern to a small-space setup.',
    'Strength',
    array['upper_pull'],
    array['shoulders', 'thoracic_spine'],
    array['home_friendly'],
    array['Home Office', 'Living Room', 'Gym'],
    array['Shoulder Injury'],
    false,
    true,
    false,
    'band-row'
  ),
  (
    'Standing Ankle Mobility Snack',
    3,
    'low',
    array['Wall Space'],
    array['Face the wall in a staggered stance', 'Drive the front knee toward the wall gently', 'Repeat 8 reps per side', 'Finish with calf stretches'],
    'A quick choice before a walk or after sitting too long.',
    'Mobility',
    array['ankle_mobility'],
    array['ankles_calves'],
    array['office_friendly', 'low_sweat'],
    array['Workplace', 'Home Office', 'Outdoor Space'],
    array['Ankle Issues'],
    false,
    true,
    true,
    'ankle-mobility'
  ),
  (
    'Lunch Break Dumbbell Carry',
    12,
    'medium',
    array['Dumbbells'],
    array['Hold one or two dumbbells by your sides', 'Walk slowly around the room for 30 seconds', 'Rest for 20 seconds', 'Repeat 6 rounds'],
    'Simple loaded work that fits a short strength break.',
    'Strength',
    array['core', 'gait_or_march'],
    array['core', 'shoulders'],
    array['home_friendly'],
    array['Living Room', 'Gym'],
    array['Back Pain', 'Shoulder Injury'],
    false,
    true,
    false,
    'loaded-carry'
  ),
  (
    'Soft Landing Evening Stretch',
    15,
    'low',
    array['Yoga Mat'],
    array['Sit comfortably on the mat', 'Perform a seated side bend each way', 'Move into a gentle figure-four stretch', 'Finish with one minute of quiet breathing'],
    'A recovery-first snack for winding down at the end of the day.',
    'Recovery',
    array['hip_mobility', 'rotation'],
    array['hips_glutes', 'low_back'],
    array['home_friendly'],
    array['Bedroom', 'Living Room'],
    array['Hip Pain', 'Knee Issues'],
    true,
    false,
    true,
    'evening-stretch'
  ),
  (
    'Chair-Assisted Squat Practice',
    7,
    'low',
    array['Chair'],
    array['Stand in front of the chair', 'Sit down slowly', 'Stand back up with control', 'Repeat for 10 reps'],
    'A beginner-friendly lower-body pattern builder.',
    'Strength',
    array['squat_pattern'],
    array['hips_glutes', 'knees'],
    array['home_friendly', 'low_sweat'],
    array['Home Office', 'Living Room', 'Bedroom'],
    array['Knee Issues'],
    false,
    true,
    true,
    'chair-squat'
  ),
  (
    'No-Floor Core Standing Press',
    5,
    'low',
    array['Resistance Bands'],
    array['Hold the band at chest height', 'Press straight out in front of you', 'Resist rotation for 8 reps', 'Switch sides and repeat'],
    'Core work for people who do not want to get down on the floor.',
    'Activation',
    array['core', 'rotation'],
    array['core'],
    array['office_friendly', 'low_sweat', 'standing_only'],
    array['Home Office', 'Living Room', 'Gym'],
    array['Shoulder Injury'],
    false,
    true,
    true,
    'standing-band-core'
  ),
  (
    'Wall Reach Thoracic Opener',
    5,
    'low',
    array['Wall Space'],
    array['Place one hand on the wall at shoulder height', 'Rotate your chest away gently', 'Return to neutral', 'Repeat 8 reps per side'],
    'Helps undo the rounded posture that builds through the day.',
    'Mobility',
    array['rotation', 'shoulder_mobility'],
    array['thoracic_spine', 'shoulders'],
    array['office_friendly', 'low_sweat', 'small_space'],
    array['Workplace', 'Home Office', 'Living Room'],
    array['Shoulder Injury'],
    false,
    true,
    true,
    'thoracic-opener'
  ),
  (
    'Floor Core Breathing Ladder',
    12,
    'low',
    array['Floor Space', 'Yoga Mat'],
    array['Lie on your back with feet elevated on a chair', 'Take 5 slow breaths into the ribs', 'Lower feet and perform 8 heel taps', 'Repeat 3 rounds'],
    'Blends recovery and trunk stability in one gentle session.',
    'Recovery',
    array['core'],
    array['core', 'low_back'],
    array['home_friendly'],
    array['Living Room', 'Bedroom'],
    array['Hip Pain'],
    true,
    false,
    true,
    'floor-core-breathing'
  ),
  (
    'Pull-Up Bar Scap Prep',
    5,
    'medium',
    array['Doorway Pull-up Bar'],
    array['Grip the bar with feet on the floor or a stool', 'Perform 8 scapular pulls', 'Rest for 20 seconds', 'Repeat 3 rounds'],
    'A strong premium-style option without requiring full pull-ups.',
    'Strength',
    array['upper_pull'],
    array['shoulders', 'thoracic_spine'],
    array['home_friendly', 'small_space'],
    array['Bedroom', 'Home Office'],
    array['Shoulder Injury', 'Wrist Problems'],
    false,
    true,
    false,
    'pull-up-bar-prep'
  ),
  (
    'Desk Break Side-Step Recharge',
    3,
    'low',
    array['None / Bodyweight Only'],
    array['Step side to side for 45 seconds', 'Reach the arms across the body', 'Repeat for 2 rounds'],
    'Adds variety when marching in place is feeling stale.',
    'Activation',
    array['lateral_shift'],
    array['hips_glutes', 'core'],
    array['office_friendly', 'low_sweat', 'camera_safe'],
    array['Workplace', 'Home Office'],
    array['Knee Issues', 'Ankle Issues'],
    false,
    true,
    true,
    'side-step-recharge'
  ),
  (
    'Chair Figure-Four Reset',
    5,
    'low',
    array['Chair'],
    array['Sit tall in the chair', 'Cross one ankle over the opposite knee', 'Lean forward slightly', 'Hold 20 seconds and switch sides'],
    'A classic seated hip opener for long desk days.',
    'Recovery',
    array['hip_mobility'],
    array['hips_glutes', 'low_back'],
    array['office_friendly', 'low_sweat'],
    array['Workplace', 'Home Office', 'Living Room'],
    array['Hip Pain', 'Knee Issues'],
    false,
    false,
    true,
    'chair-figure-four'
  ),
  (
    'Mat Dead Bug Builder',
    7,
    'medium',
    array['Yoga Mat', 'Floor Space'],
    array['Lie on your back with knees over hips', 'Lower opposite arm and leg slowly', 'Return to center', 'Perform 8 reps per side'],
    'Core strength without needing flashy movements.',
    'Strength',
    array['core'],
    array['core', 'low_back'],
    array['home_friendly'],
    array['Living Room', 'Bedroom'],
    array['Back Pain'],
    true,
    false,
    false,
    'dead-bug'
  ),
  (
    'Wall Lean Calf Recovery',
    5,
    'low',
    array['Wall Space'],
    array['Place both hands on the wall', 'Step one foot back', 'Press the heel down for 20 seconds', 'Switch sides and repeat 3 rounds'],
    'A gentle option after a long walk or a long day on your feet.',
    'Recovery',
    array['ankle_mobility'],
    array['ankles_calves'],
    array['office_friendly', 'low_sweat'],
    array['Workplace', 'Home Office', 'Outdoor Space'],
    array[]::text[],
    false,
    true,
    true,
    'calf-recovery'
  ),
  (
    'Countertop Shoulder Tap Series',
    7,
    'medium',
    array['Countertop'],
    array['Set up in an incline plank on the countertop', 'Tap one shoulder at a time for 20 reps', 'Rest for 20 seconds', 'Repeat 3 rounds'],
    'A practical way to train anti-rotation and upper-body stability.',
    'Strength',
    array['core', 'upper_push'],
    array['core', 'shoulders'],
    array['home_friendly', 'small_space'],
    array['Home Office', 'Living Room'],
    array['Shoulder Injury', 'Wrist Problems'],
    false,
    true,
    false,
    'countertop-shoulder-taps'
  ),
  (
    'Standing Hamstring Sweep',
    5,
    'low',
    array['None / Bodyweight Only'],
    array['Step one heel forward', 'Sweep both hands toward the toes', 'Return to standing', 'Alternate sides for 10 reps each'],
    'A simple posterior-chain reset when your legs feel heavy.',
    'Mobility',
    array['hip_hinge'],
    array['hips_glutes', 'low_back'],
    array['office_friendly', 'low_sweat'],
    array['Workplace', 'Home Office', 'Outdoor Space'],
    array['Back Pain'],
    false,
    true,
    true,
    'standing-hamstring'
  ),
  (
    'Wall Angel Reset',
    5,
    'low',
    array['Wall Space'],
    array['Stand with your back against the wall', 'Slide the arms up and down slowly', 'Pause at the top for one breath', 'Repeat for 10 reps'],
    'Great for resetting slumped shoulders and upper-back stiffness.',
    'Mobility',
    array['shoulder_mobility'],
    array['shoulders', 'thoracic_spine'],
    array['office_friendly', 'camera_safe', 'low_sweat'],
    array['Workplace', 'Home Office', 'Living Room'],
    array['Shoulder Injury'],
    false,
    true,
    true,
    'wall-angel'
  ),
  (
    'Chair March Intervals',
    7,
    'low',
    array['Chair'],
    array['Sit tall and brace the core', 'March the knees for 30 seconds', 'Rest for 15 seconds', 'Repeat 6 rounds'],
    'An easy-entry cardio snack for lower-energy days.',
    'Activation',
    array['gait_or_march', 'core'],
    array['core', 'hips_glutes'],
    array['office_friendly', 'low_sweat', 'camera_safe'],
    array['Workplace', 'Home Office'],
    array['Hip Pain'],
    false,
    false,
    true,
    'chair-march'
  ),
  (
    'Band Good Morning Primer',
    7,
    'medium',
    array['Resistance Bands'],
    array['Stand on the middle of the band', 'Hold the ends at shoulder height', 'Hinge at the hips for 10 reps', 'Repeat 3 rounds'],
    'A scalable hinge pattern when dumbbells are not available.',
    'Strength',
    array['hip_hinge'],
    array['hips_glutes', 'low_back'],
    array['home_friendly'],
    array['Living Room', 'Gym', 'Home Office'],
    array['Back Pain', 'Hip Pain'],
    false,
    true,
    false,
    'band-good-morning'
  ),
  (
    'Bedroom Wind-Down Breathing Flow',
    10,
    'low',
    array['Yoga Mat'],
    array['Lie down comfortably', 'Take 5 slow diaphragmatic breaths', 'Add a gentle knee sway side to side', 'Finish with one hand on chest and one on belly'],
    'A calming transition from work mode to rest mode.',
    'Recovery',
    array['rotation', 'core'],
    array['low_back', 'core'],
    array['home_friendly'],
    array['Bedroom'],
    array[]::text[],
    true,
    false,
    true,
    'bedroom-breathing'
  ),
  (
    'Supported Single-Leg Reach',
    5,
    'low',
    array['Chair'],
    array['Stand beside a chair', 'Reach one leg back lightly', 'Tip forward slightly from the hips', 'Return to standing and repeat 8 reps each side'],
    'Balance practice that still feels approachable.',
    'Activation',
    array['balance', 'hip_hinge'],
    array['hips_glutes', 'core'],
    array['office_friendly', 'low_sweat'],
    array['Home Office', 'Living Room', 'Workplace'],
    array['Ankle Issues', 'Hip Pain'],
    false,
    true,
    true,
    'single-leg-reach'
  ),
  (
    'Countertop Plank Breathing Hold',
    3,
    'medium',
    array['Countertop'],
    array['Place forearms on the countertop', 'Step back into a long body line', 'Hold for 20 seconds', 'Rest and repeat 3 rounds'],
    'A crisp total-body challenge for short breaks.',
    'Strength',
    array['core'],
    array['core', 'shoulders'],
    array['home_friendly', 'small_space'],
    array['Home Office', 'Living Room'],
    array['Shoulder Injury', 'Wrist Problems'],
    false,
    true,
    false,
    'countertop-plank'
  ),
  (
    'Couch-to-Desk Mobility Recharge',
    7,
    'low',
    array['None / Bodyweight Only'],
    array['Stand tall and reach both arms overhead', 'Perform 8 slow side bends per side', 'Add 10 thoracic rotations', 'Finish with 3 long exhales'],
    'Built for the end of a long sitting block when you need to loosen up fast.',
    'Mobility',
    array['spinal_mobility', 'rotation'],
    array['thoracic_spine', 'low_back'],
    array['office_friendly', 'low_sweat'],
    array['Workplace', 'Home Office', 'Living Room'],
    array[]::text[],
    false,
    true,
    true,
    'couch-desk-recharge'
  ),
  (
    'Band Core Press Ladder',
    7,
    'medium',
    array['Resistance Bands'],
    array['Anchor the band at chest height', 'Press straight out for 8 reps per side', 'Hold the last rep for 10 seconds', 'Repeat 3 rounds'],
    'A compact anti-rotation set when you want more challenge than a reset snack.',
    'Strength',
    array['core', 'rotation'],
    array['core'],
    array['home_friendly', 'small_space'],
    array['Home Office', 'Living Room', 'Gym'],
    array['Shoulder Injury'],
    false,
    true,
    false,
    'band-core-press'
  ),
  (
    'Doorway Pull Prep Hold',
    5,
    'medium',
    array['Doorway Pull-up Bar'],
    array['Grip the bar with feet supported on the floor', 'Hold a tall hollow position for 15 seconds', 'Perform 5 scap pulls', 'Repeat 3 rounds'],
    'A premium-feeling pull session without needing full pull-ups.',
    'Strength',
    array['upper_pull'],
    array['shoulders', 'core'],
    array['home_friendly', 'small_space'],
    array['Bedroom', 'Home Office'],
    array['Shoulder Injury', 'Wrist Problems'],
    false,
    true,
    false,
    'doorway-pull-prep'
  ),
  (
    'Floor Rotation Reset',
    10,
    'low',
    array['Floor Space', 'Yoga Mat'],
    array['Lie on your back with knees bent', 'Drop the knees side to side slowly', 'Add 5 long breaths each direction', 'Finish with a gentle knee hug'],
    'A low-stimulation recovery snack for the end of the day.',
    'Recovery',
    array['rotation', 'spinal_mobility'],
    array['low_back', 'core'],
    array['home_friendly'],
    array['Bedroom', 'Living Room'],
    array['Hip Pain'],
    true,
    false,
    true,
    'floor-rotation-reset'
  ),
  (
    'Standing Shoulder Buffer',
    5,
    'low',
    array['Wall Space'],
    array['Stand beside a wall', 'Perform 10 wall-assisted arm circles', 'Do 8 wall slides', 'Finish with a chest opener'],
    'Useful between meetings when your shoulders feel loaded from typing.',
    'Recovery',
    array['shoulder_mobility'],
    array['shoulders', 'neck_upper_back'],
    array['office_friendly', 'camera_safe', 'low_sweat'],
    array['Workplace', 'Home Office'],
    array['Shoulder Injury'],
    false,
    true,
    true,
    'standing-shoulder-buffer'
  ),
  (
    'Dumbbell Tempo Squat Snack',
    10,
    'medium',
    array['Dumbbells'],
    array['Hold one dumbbell at chest height', 'Lower into a controlled squat for 3 counts', 'Stand tall', 'Complete 8 reps for 3 rounds'],
    'For days when you want a more strength-forward snack in a short window.',
    'Strength',
    array['squat_pattern'],
    array['hips_glutes', 'knees'],
    array['home_friendly'],
    array['Living Room', 'Gym'],
    array['Knee Issues', 'Hip Pain'],
    false,
    true,
    false,
    'dumbbell-tempo-squat'
  ),
  (
    'Countertop Recovery Fold',
    5,
    'low',
    array['Countertop'],
    array['Place both hands on the countertop', 'Step back and lengthen the spine', 'Bend the knees softly', 'Hold for 3 slow breaths and repeat'],
    'A no-floor decompression option for home-office days.',
    'Recovery',
    array['hip_hinge', 'spinal_mobility'],
    array['low_back', 'thoracic_spine'],
    array['home_friendly', 'low_sweat'],
    array['Home Office', 'Living Room'],
    array['Back Pain'],
    false,
    true,
    true,
    'countertop-recovery-fold'
  ),
  (
    'Chair Balance and Reach Flow',
    7,
    'low',
    array['Chair'],
    array['Stand behind the chair', 'Lift one knee and hold for 15 seconds', 'Reach the opposite arm overhead', 'Switch sides and repeat 3 rounds'],
    'A gentle coordination snack when you want balance work without much intensity.',
    'Activation',
    array['balance'],
    array['ankles_calves', 'core'],
    array['office_friendly', 'low_sweat'],
    array['Workplace', 'Home Office', 'Living Room'],
    array['Ankle Issues'],
    false,
    true,
    true,
    'chair-balance-reach'
  )
;
