// ─── Space Analysis ───────────────────────────────────────────────────────────

export type ImageMimeType = 'image/jpeg' | 'image/png' | 'image/webp' | 'image/gif';

export interface SpaceAnalysisInput {
  imageBase64: string;
  mimeType: ImageMimeType;
  /** User's physical limitations (e.g. ["Knee Issues", "Back Pain"]).
   *  When present the AI must avoid exercises that aggravate these conditions. */
  limitations?: string[];
}

/** Physical overview of the space — displayed as context to the user. */
export interface SpaceOverview {
  dimensions: string;
  usableSpace: string;
  detectedEquipment: string[];
  floorType: string;
  obstacles: string[];
  safetyNotes: string[];
}

/**
 * A fully-structured exercise generated by AI.
 * Shape mirrors the `exercises` DB table so rows can be inserted directly.
 */
export interface GeneratedExercise {
  title: string;
  /** Duration in minutes. */
  duration: number;
  intensity: 'low' | 'medium';
  equipment: string[];
  instructions: string[];
  tips: string;
  category: string;
  movement_tags: string[];
  body_region_tags: string[];
  context_tags: string[];
  location_tags: string[];
  contraindication_tags: string[];
  requires_floor: boolean;
  standing_only: boolean;
  no_sweat: boolean;
}

export interface SpaceAnalysisOutput {
  overview: SpaceOverview;
  exercises: GeneratedExercise[];
}

// ─── Capability interfaces ────────────────────────────────────────────────────
// One interface per AI task. Each can be backed by a different model/provider.
// New capabilities are added here as they are implemented.

export interface SpaceAnalysisCapability {
  analyzeSpace(input: SpaceAnalysisInput): Promise<SpaceAnalysisOutput>;
}
