insert into public.exercises (
  title, duration_minutes, intensity, equipment, instructions, tips, category,
  movement_tags, body_region_tags, context_tags, location_tags, contraindication_tags,
  requires_floor, standing_only, no_sweat, variation_key
)
select *
from (
values
  (
    'Kettlebell Deadlift Tempo Set',
    12,
    'medium',
    array['Kettlebells'],
    array['Set feet shoulder-width apart with kettlebell centered', 'Lower with a 3-second hinge', 'Stand tall and squeeze glutes', 'Complete 8 reps for 3 rounds'],
    'Controlled tempo reinforces hinge mechanics and back-friendly loading.',
    'Strength',
    array['hip_hinge'],
    array['hips_glutes', 'low_back', 'core'],
    array['home_friendly'],
    array['Living Room', 'Gym'],
    array['Back Pain'],
    false,
    true,
    false,
    'kettlebell-deadlift-tempo-set'
  ),
  (
    'Kettlebell Suitcase Carry March',
    5,
    'medium',
    array['Kettlebells'],
    array['Hold kettlebell at your side', 'March in place for 30 seconds', 'Switch sides', 'Repeat 4 rounds'],
    'Anti-tilt core training in a compact office-friendly format.',
    'Activation',
    array['core', 'gait_or_march'],
    array['core', 'hips_glutes'],
    array['small_space', 'home_friendly'],
    array['Home Office', 'Living Room'],
    array['Hip Pain'],
    false,
    true,
    false,
    'kettlebell-suitcase-carry-march'
  ),
  (
    'Kettlebell Halo Mobility Flow',
    7,
    'low',
    array['Kettlebells'],
    array['Hold light kettlebell by the horns', 'Circle around head slowly for 6 reps', 'Reverse direction for 6 reps', 'Repeat 3 rounds'],
    'Great shoulder and upper-back mobility sequence with a single bell.',
    'Mobility',
    array['shoulder_mobility', 'rotation'],
    array['shoulders', 'thoracic_spine'],
    array['home_friendly', 'low_sweat'],
    array['Home Office', 'Living Room', 'Gym'],
    array['Shoulder Injury'],
    false,
    true,
    true,
    'kettlebell-halo-mobility-flow'
  ),
  (
    'Kettlebell Reverse Lunge Alternating',
    10,
    'medium',
    array['Kettlebells'],
    array['Hold one kettlebell goblet-style', 'Step back into reverse lunge', 'Alternate sides for 8 reps each', 'Repeat 3 rounds'],
    'Unilateral leg strength and balance in a concise progression block.',
    'Strength',
    array['lunge_pattern', 'balance'],
    array['hips_glutes', 'knees', 'core'],
    array['home_friendly'],
    array['Living Room', 'Gym'],
    array['Knee Issues', 'Ankle Issues'],
    false,
    true,
    false,
    'kettlebell-reverse-lunge-alternating'
  ),
  (
    'Kettlebell Power Swing Intervals',
    7,
    'medium',
    array['Kettlebells'],
    array['Perform 15 kettlebell swings', 'Rest for 30 seconds', 'Repeat for 5 rounds', 'Cool down with deep breathing'],
    'Power-focused hinge intervals for quick posterior-chain work.',
    'Cardio',
    array['hip_hinge', 'cardio'],
    array['hips_glutes', 'cardio_endurance'],
    array['home_friendly'],
    array['Gym', 'Living Room'],
    array['Back Pain'],
    false,
    true,
    false,
    'kettlebell-power-swing-intervals'
  ),
  (
    'Kettlebell Windmill Mobility Drill',
    8,
    'low',
    array['Kettlebells'],
    array['Press kettlebell overhead with one arm', 'Hinge and rotate toward the floor', 'Return to standing with control', 'Complete 5 reps per side for 2 rounds'],
    'Combines thoracic mobility, shoulder stability, and hip control.',
    'Mobility',
    array['rotation', 'shoulder_mobility', 'hip_hinge'],
    array['thoracic_spine', 'shoulders', 'hips_glutes'],
    array['home_friendly'],
    array['Gym', 'Living Room'],
    array['Shoulder Injury', 'Back Pain'],
    false,
    true,
    true,
    'kettlebell-windmill-mobility-drill'
  ),
  (
    'Jump Rope Sprint Pyramid',
    10,
    'medium',
    array['Jump Rope'],
    array['Jump 20 seconds then rest 20', 'Jump 30 seconds then rest 20', 'Jump 40 seconds then rest 20', 'Repeat pyramid twice'],
    'Structured speed ladder that scales cardio intensity quickly.',
    'Cardio',
    array['cardio'],
    array['cardio_endurance', 'ankles_calves'],
    array['outdoor_friendly'],
    array['Outdoor Space', 'Gym'],
    array['Ankle Issues'],
    false,
    true,
    false,
    'jump-rope-sprint-pyramid'
  ),
  (
    'Jump Rope Recovery Bounce',
    3,
    'low',
    array['Jump Rope'],
    array['Do gentle rope skips for 20 seconds', 'Rest for 20 seconds', 'Repeat 4 rounds', 'Finish with calf stretch'],
    'Low-intensity rhythm option for quick movement snacks.',
    'Recovery',
    array['cardio'],
    array['ankles_calves'],
    array['low_sweat', 'outdoor_friendly'],
    array['Outdoor Space', 'Home Office'],
    array['Ankle Issues'],
    false,
    true,
    true,
    'jump-rope-recovery-bounce'
  ),
  (
    'Jump Rope Lateral Step Sequence',
    6,
    'medium',
    array['Jump Rope'],
    array['Step side to side while skipping rope', 'Work for 30 seconds then rest 20', 'Repeat 6 rounds', 'Cool down with deep breaths'],
    'Adds frontal-plane variety while keeping rope cadence moderate.',
    'Activation',
    array['cardio', 'balance'],
    array['ankles_calves', 'hips_glutes'],
    array['outdoor_friendly', 'home_friendly'],
    array['Gym', 'Outdoor Space', 'Living Room'],
    array['Ankle Issues'],
    false,
    true,
    false,
    'jump-rope-lateral-step-sequence'
  ),
  (
    'Jump Rope Coordination Ladder',
    8,
    'medium',
    array['Jump Rope'],
    array['Round 1 basic bounce for 30 seconds', 'Round 2 alternate foot step for 30 seconds', 'Round 3 high-knee rope for 20 seconds', 'Repeat ladder 3 times'],
    'Progressive coordination ladder to keep sessions engaging.',
    'Activation',
    array['cardio', 'gait_or_march'],
    array['cardio_endurance', 'ankles_calves'],
    array['outdoor_friendly'],
    array['Gym', 'Outdoor Space'],
    array['Ankle Issues'],
    false,
    true,
    false,
    'jump-rope-coordination-ladder'
  ),
  (
    'Jump Rope Calf-Endurance Builder',
    12,
    'medium',
    array['Jump Rope'],
    array['Skip rope for 40 seconds', 'Rest 20 seconds', 'Repeat 10 rounds', 'Walk for 60 seconds to recover'],
    'Longer interval block for lower-leg endurance and aerobic capacity.',
    'Cardio',
    array['cardio'],
    array['ankles_calves', 'cardio_endurance'],
    array['outdoor_friendly'],
    array['Outdoor Space', 'Gym'],
    array['Ankle Issues'],
    false,
    true,
    false,
    'jump-rope-calf-endurance-builder'
  ),
  (
    'Jump Rope Single-Leg Skill Primer',
    7,
    'medium',
    array['Jump Rope'],
    array['Skip on both feet for 20 seconds', 'Switch to right-foot hops for 10 seconds', 'Switch to left-foot hops for 10 seconds', 'Repeat 6 rounds'],
    'Skill-focused rope session that improves balance and control.',
    'Activation',
    array['cardio', 'balance'],
    array['ankles_calves', 'core'],
    array['outdoor_friendly'],
    array['Gym', 'Outdoor Space'],
    array['Ankle Issues'],
    false,
    true,
    false,
    'jump-rope-single-leg-skill-primer'
  )
) as seed (
  title, duration_minutes, intensity, equipment, instructions, tips, category,
  movement_tags, body_region_tags, context_tags, location_tags, contraindication_tags,
  requires_floor, standing_only, no_sweat, variation_key
)
where not exists (
  select 1 from public.exercises existing where existing.title = seed.title
);

